CREATE TABLE IF NOT EXISTS `ddl` (
    `Column_1` VARCHAR(104) CHARACTER SET utf8,
    `Column_2` VARCHAR(68) CHARACTER SET utf8,
    `Column_3` VARCHAR(20) CHARACTER SET utf8
);

INSERT INTO `ddl` VALUES (NULL, NULL, NULL),
    (NULL, NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE booking (', NULL, NULL),
    ('    bookingid               NUMBER NOT NULL', NULL, NULL),
    ('    bookingdate             DATE NOT NULL', NULL, NULL),
    ('    status                  VARCHAR2(15) NOT NULL', NULL, NULL),
    ('    passenger_passengerid   NUMBER', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE booking ADD CONSTRAINT booking_pk PRIMARY KEY ( bookingid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE cargo (', NULL, NULL),
    ('    cargoid         NUMBER NOT NULL', NULL, NULL),
    ('    weight          VARCHAR2(100)', NULL, NULL),
    ('    destination     VARCHAR2(100)', NULL, NULL),
    ('    train_trainid   NUMBER', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE cargo ADD CONSTRAINT cargo_pk PRIMARY KEY ( cargoid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE department (', NULL, NULL),
    ('    departmentid     NUMBER NOT NULL', NULL, NULL),
    ('    departmentname   VARCHAR2(100) NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE department ADD CONSTRAINT department_pk PRIMARY KEY ( departmentid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE employee (', NULL, NULL),
    ('    employeeid                NUMBER NOT NULL', NULL, NULL),
    ('    name                      VARCHAR2(50) NOT NULL', NULL, NULL),
    ('    role                      VARCHAR2(20) NOT NULL', NULL, NULL),
    ('    department_departmentid   NUMBER', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employeeid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE passenger (', NULL, NULL),
    ('    passengerid      NUMBER NOT NULL', NULL, NULL),
    ('    passenger_name   VARCHAR2(50) NOT NULL', NULL, NULL),
    ('    age              NUMBER NOT NULL', NULL, NULL),
    ('    gender           VARCHAR2(8) NOT NULL', NULL, NULL),
    ('    contact_phone    NUMBER', NULL, NULL),
    ('    email            VARCHAR2(50)', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( passengerid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE relation_5 (', NULL, NULL),
    ('    train_trainid   NUMBER NOT NULL', NULL, NULL),
    ('    route_routeid   NUMBER NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_5 ADD CONSTRAINT relation_5_pk PRIMARY KEY ( train_trainid', NULL, NULL),
    ('                                                                  route_routeid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE relation_7 (', NULL, NULL),
    ('    station_stationid   NUMBER NOT NULL', NULL, NULL),
    ('    route_routeid       NUMBER NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_7 ADD CONSTRAINT relation_7_pk PRIMARY KEY ( station_stationid', NULL, NULL),
    ('                                                                  route_routeid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE relation_8 (', NULL, NULL),
    ('    schedule_scheduleid   NUMBER NOT NULL', NULL, NULL),
    ('    station_stationid     NUMBER NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_8 ADD CONSTRAINT relation_8_pk PRIMARY KEY ( schedule_scheduleid', NULL, NULL),
    ('                                                                  station_stationid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE relation_9 (', NULL, NULL),
    ('    employee_employeeid   NUMBER NOT NULL', NULL, NULL),
    ('    train_trainid         NUMBER NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_9 ADD CONSTRAINT relation_9_pk PRIMARY KEY ( employee_employeeid', NULL, NULL),
    ('                                                                  train_trainid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE route (', NULL, NULL),
    ('    routeid            NUMBER NOT NULL', NULL, NULL),
    ('    routename          VARCHAR2(50) NOT NULL', NULL, NULL),
    ('    starting_station   VARCHAR2(50) NOT NULL', NULL, NULL),
    ('    ending_station     VARCHAR2(50) NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    ('CREATE SEQUENCE Booking_ID', NULL, NULL),
    ('  START WITH 10000000   -- Start from 8 digits', NULL, NULL),
    ('  INCREMENT BY 1        -- Increment by 1 each time', NULL, NULL),
    (' ;             ', NULL, NULL),
    (NULL, NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE route ADD CONSTRAINT route_pk PRIMARY KEY ( routeid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE schedule (', NULL, NULL),
    ('    scheduleid      NUMBER NOT NULL', NULL, NULL),
    ('    arrivaltime     DATE NOT NULL', NULL, NULL),
    ('    departuretime   DATE NOT NULL', NULL, NULL),
    ('    train_trainid   NUMBER', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE schedule ADD CONSTRAINT schedule_pk PRIMARY KEY ( scheduleid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE station (', NULL, NULL),
    ('    stationid      NUMBER NOT NULL', NULL, NULL),
    ('    station_name   VARCHAR2(50) NOT NULL', NULL, NULL),
    ('    location       VARCHAR2(50) NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE station ADD CONSTRAINT station_pk PRIMARY KEY ( stationid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE ticket (', NULL, NULL),
    ('    ticketid            NUMBER NOT NULL', NULL, NULL),
    ('    seat_number         VARCHAR2(50) NOT NULL', NULL, NULL),
    ('    price               NUMBER(2) NOT NULL', NULL, NULL),
    ('    travel_date         TIMESTAMP WITH LOCAL TIME ZONE NOT NULL', NULL, NULL),
    ('    booking_bookingid   NUMBER', NULL, NULL),
    ('    train_trainid       NUMBER', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE ticket ADD CONSTRAINT ticket_pk PRIMARY KEY ( ticketid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE train (', NULL, NULL),
    ('    trainid     NUMBER NOT NULL', NULL, NULL),
    ('    trainname   VARCHAR2(25) NOT NULL', NULL, NULL),
    ('    capacity    NUMBER NOT NULL', NULL, NULL),
    ('    traintype   VARCHAR2(15) NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE train ADD CONSTRAINT train_pk PRIMARY KEY ( trainid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE booking', NULL, NULL),
    ('    ADD CONSTRAINT booking_passenger_fk FOREIGN KEY ( passenger_passengerid )', NULL, NULL),
    ('        REFERENCES passenger ( passengerid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE cargo', NULL, NULL),
    ('    ADD CONSTRAINT cargo_train_fk FOREIGN KEY ( train_trainid )', NULL, NULL),
    ('        REFERENCES train ( trainid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE employee', NULL, NULL),
    ('    ADD CONSTRAINT employee_department_fk FOREIGN KEY ( department_departmentid )', NULL, NULL),
    ('        REFERENCES department ( departmentid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_5', NULL, NULL),
    ('    ADD CONSTRAINT relation_5_route_fk FOREIGN KEY ( route_routeid )', NULL, NULL),
    ('        REFERENCES route ( routeid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_5', NULL, NULL),
    ('    ADD CONSTRAINT relation_5_train_fk FOREIGN KEY ( train_trainid )', NULL, NULL),
    ('        REFERENCES train ( trainid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_7', NULL, NULL),
    ('    ADD CONSTRAINT relation_7_route_fk FOREIGN KEY ( route_routeid )', NULL, NULL),
    ('        REFERENCES route ( routeid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_7', NULL, NULL),
    ('    ADD CONSTRAINT relation_7_station_fk FOREIGN KEY ( station_stationid )', NULL, NULL),
    ('        REFERENCES station ( stationid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_8', NULL, NULL),
    ('    ADD CONSTRAINT relation_8_schedule_fk FOREIGN KEY ( schedule_scheduleid )', NULL, NULL),
    ('        REFERENCES schedule ( scheduleid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_8', NULL, NULL),
    ('    ADD CONSTRAINT relation_8_station_fk FOREIGN KEY ( station_stationid )', NULL, NULL),
    ('        REFERENCES station ( stationid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_9', NULL, NULL),
    ('    ADD CONSTRAINT relation_9_employee_fk FOREIGN KEY ( employee_employeeid )', NULL, NULL),
    ('        REFERENCES employee ( employeeid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE relation_9', NULL, NULL),
    ('    ADD CONSTRAINT relation_9_train_fk FOREIGN KEY ( train_trainid )', NULL, NULL),
    ('        REFERENCES train ( trainid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE schedule', NULL, NULL),
    ('    ADD CONSTRAINT schedule_train_fk FOREIGN KEY ( train_trainid )', NULL, NULL),
    ('        REFERENCES train ( trainid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE ticket', NULL, NULL),
    ('    ADD CONSTRAINT ticket_booking_fk FOREIGN KEY ( booking_bookingid )', NULL, NULL),
    ('        REFERENCES booking ( bookingid );', NULL, NULL),
    (NULL, NULL, NULL),
    ('ALTER TABLE ticket', NULL, NULL),
    ('    ADD CONSTRAINT ticket_train_fk FOREIGN KEY ( train_trainid )', NULL, NULL),
    ('        REFERENCES train ( trainid );', NULL, NULL),
    (NULL, NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE OR REPLACE TRIGGER trg_adjust_train_capacity', NULL, NULL),
    ('AFTER INSERT OR DELETE ON cargo', NULL, NULL),
    ('FOR EACH ROW', NULL, NULL),
    ('DECLARE', NULL, NULL),
    ('    v_train_capacity NUMBER;', NULL, NULL),
    ('BEGIN', NULL, NULL),
    ('    IF INSERTING THEN', NULL, NULL),
    ('        -- Get current train capacity', NULL, NULL),
    ('        SELECT capacity INTO v_train_capacity FROM train WHERE trainid = :NEW.train_trainid;', NULL, NULL),
    ('        -- Update the train capacity', NULL, NULL),
    ('        UPDATE train SET capacity = v_train_capacity - :NEW.weight WHERE trainid = :NEW.train_trainid;', NULL, NULL),
    ('    ELSIF DELETING THEN', NULL, NULL),
    ('        -- Get current train capacity', NULL, NULL),
    ('        SELECT capacity INTO v_train_capacity FROM train WHERE trainid = :OLD.train_trainid;', NULL, NULL),
    ('        -- Update the train capacity', NULL, NULL),
    ('        UPDATE train SET capacity = v_train_capacity + :OLD.weight WHERE trainid = :OLD.train_trainid;', NULL, NULL),
    ('    END IF;', NULL, NULL),
    ('END;', NULL, NULL),
    ('/', NULL, NULL),
    (NULL, NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE OR REPLACE TRIGGER trg_update_booking_status', NULL, NULL),
    ('AFTER UPDATE OR INSERT ON ticket', NULL, NULL),
    ('FOR EACH ROW', NULL, NULL),
    ('BEGIN', NULL, NULL),
    ('    IF :NEW.travel_date < SYSDATE THEN', NULL, NULL),
    ('        UPDATE booking', NULL, NULL),
    ('        SET status = ''Completed''', NULL, NULL),
    ('        WHERE bookingid = :NEW.booking_bookingid;', NULL, NULL),
    ('    END IF;', NULL, NULL),
    ('END;', NULL, NULL),
    ('/', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE OR REPLACE TRIGGER trg_check_employee_department', NULL, NULL),
    ('BEFORE INSERT OR UPDATE ON employee', NULL, NULL),
    ('FOR EACH ROW', NULL, NULL),
    ('BEGIN', NULL, NULL),
    ('    IF :NEW.department_departmentid IS NULL THEN', NULL, NULL),
    ('        RAISE_APPLICATION_ERROR(-20002', ''Employee must be assigned to a department.'');', NULL),
    ('    END IF;', NULL, NULL),
    ('END;', NULL, NULL),
    ('/', NULL, NULL),
    ('CREATE OR REPLACE TRIGGER trg_prevent_duplicate_booking', NULL, NULL),
    ('BEFORE INSERT OR UPDATE ON ticket', NULL, NULL),
    ('FOR EACH ROW', NULL, NULL),
    ('DECLARE', NULL, NULL),
    ('    v_count NUMBER;', NULL, NULL),
    ('BEGIN', NULL, NULL),
    ('    SELECT COUNT(*)', NULL, NULL),
    ('    INTO v_count', NULL, NULL),
    ('    FROM ticket t', NULL, NULL),
    ('    JOIN booking b ON t.booking_bookingid = b.bookingid', NULL, NULL),
    ('    WHERE b.passenger_passengerid = :NEW.booking_bookingid', NULL, NULL),
    ('      AND t.train_trainid = :NEW.train_trainid', NULL, NULL),
    ('      AND t.travel_date = :NEW.travel_date;', NULL, NULL),
    (NULL, NULL, NULL),
    ('    IF v_count > 0 THEN', NULL, NULL),
    ('        RAISE_APPLICATION_ERROR(-20003', ''Passenger already has a booking for this train and travel date.'');', NULL),
    ('    END IF;', NULL, NULL),
    ('END;', NULL, NULL),
    ('/', NULL, NULL),
    (NULL, NULL, NULL);
    
INSERT INTO `ddl` VALUES ('CREATE OR REPLACE TRIGGER trg_update_train_seat_availability', NULL, NULL),
    ('AFTER INSERT OR DELETE ON ticket', NULL, NULL),
    ('FOR EACH ROW', NULL, NULL),
    ('DECLARE', NULL, NULL),
    ('    v_train_capacity NUMBER;', NULL, NULL),
    ('BEGIN', NULL, NULL),
    ('    IF INSERTING THEN', NULL, NULL),
    ('        -- Reduce seat availability when a ticket is booked', NULL, NULL),
    ('        UPDATE train SET capacity = capacity - 1 WHERE trainid = :NEW.train_trainid;', NULL, NULL),
    ('    ELSIF DELETING THEN', NULL, NULL),
    ('        -- Increase seat availability when a ticket is canceled', NULL, NULL),
    ('        UPDATE train SET capacity = capacity + 1 WHERE trainid = :OLD.train_trainid;', NULL, NULL),
    ('    END IF;', NULL, NULL),
    ('END;', NULL, NULL),
    ('/', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE status (', NULL, NULL),
    ('    status_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', NULL, NULL),
    ('    status_name VARCHAR2(50) NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('INSERT INTO status (status_name) VALUES (''Pending'');', NULL, NULL),
    ('INSERT INTO status (status_name) VALUES (''Approved'');', NULL, NULL),
    ('INSERT INTO status (status_name) VALUES (''Cancelled'');', NULL, NULL),
    ('INSERT INTO status (status_name) VALUES (''Completed'');', NULL, NULL),
    ('INSERT INTO status (status_name) VALUES (''On Hold'');', NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE SEQUENCE Booking_ID', NULL, NULL),
    ('  START WITH 10000000   -- Start from 8 digits', NULL, NULL),
    ('  INCREMENT BY 1        -- Increment by 1 each time', NULL, NULL),
    (' ;      ', NULL, NULL),
    (NULL, NULL, NULL),
    (NULL, NULL, NULL),
    ('CREATE TABLE TRAIN_TYPE (', NULL, NULL),
    ('    TRAIN_TYPE_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', NULL, NULL),
    ('    TRAIN_TYPE_NAME VARCHAR2(100) NOT NULL', NULL, NULL),
    (');', NULL, NULL),
    (NULL, NULL, NULL),
    ('INSERT INTO TRAIN_TYPE (TRAIN_TYPE_NAME)', NULL, NULL),
    ('VALUES ', NULL, NULL),
    ('(''Passenger'');', NULL, NULL),
    (NULL, NULL, NULL),
    ('INSERT INTO TRAIN_TYPE (TRAIN_TYPE_NAME)', NULL, NULL),
    ('VALUES ', NULL, NULL),
    ('(''Cargo'');', NULL,

